name: CI

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-ngrok:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Run Batch Script
        run: |
          Invoke-WebRequest -Uri 'https://gist.githubusercontent.com/postaka129/ff22bc5829024cc9cb18448d242334e8/raw/c5975ec2bef16f8f5ecc0adc7985dac9ed5f8033/run-ngrok.bat' -OutFile run-ngrok.bat
          echo Running batch script...
          .\run-ngrok.bat ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: pwsh

      - name: Extract ngrok TCP Endpoint
        run: |
          Start-Sleep -Seconds 10 # Wait for ngrok to start
          $tunnels = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels
          $tcpTunnel = $tunnels.tunnels | Where-Object { $_.proto -eq 'tcp' }
          if ($tcpTunnel) {
            Write-Host "ngrok TCP endpoint: $($tcpTunnel.public_url)"
          } else {
            Write-Host "No TCP tunnel found."
          }
        shell: pwsh
