name: Notify Telegram on Ngrok TCP URL

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Ngrok Tunnels
      env:
        NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      run: |
        curl -H "Authorization: Bearer $NGROK_API_KEY" \
             -H "Ngrok-Version: 2" \
             https://api.ngrok.com/tunnels \
             > tunnels.json
        cat tunnels.json
      id: ngrok

    - name: Extract and Format TCP URL
      run: |
        export NGROK_TCP_URL=$(cat tunnels.json | jq -r '.tunnels[] | select(.proto=="tcp") | .public_url' | sed 's/tcp:\/\///')
        echo "NGROK_TCP_URL=$NGROK_TCP_URL" >> $GITHUB_ENV

    - name: Send Notification to Telegram
      if: env.NGROK_TCP_URL != ''
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
             -d "chat_id=${CHAT_ID}&text=TCP URL: <code>${{ env.NGROK_TCP_URL }}</code>&parse_mode=HTML"
